# Dont touch it or at least dont complain when everything burns.
# No version = 1.x
# version 1 = 2.x
version: 1
# Get a simple notify, when a new build is available. Keeping this enabled is highly recommended.
checkUpdates: true
# The refresh rate of the door state. 1 sec = 20 ticks.
# This means a refresh rate of 20 would result in a state update every second.
# That should be perfectly fine, unless you have thousands of doors.
# The amount of doors updated every tick will be  doorAmount / refresh rate or at least one.
refreshRate: 20
# Your desired language.
language: en_US
# Send anonymized metrics to bStats.
# With enabling this you allow me to see which features are used. It also motivated me to develop this plugin further.
# It also helps me to decide which feature should get an update.
enableMetrics: true
# This is the size of caches JS operations.
# If you use custom evaluators I recommend to set this to at least 200
# If you use placeholder evaluators I recommend to set this at least to 400
# If you use both I recommend to set this at least to 600
# If you have many doors with custom or placeholder evaluators you may increase this to reduce operations.
jsCacheSize: 400
# This defines the radius in which a player must be to get checked by a player condition.
# This can be seen as a global proximity condition for all doors.
# Should not be lower than 100. 200 can be considered as best value.
playerCheckRadius: 200
# We save your doors here. If it is empty you should change this :P
doors:
