name: ${name}
description: ${description}
author: Hadde
version: ${version}
main: de.eldoria.bigdoorsopener.core.BigDoorsOpener
website: www.spigotmc.org/resources/80805/
api-version: 1.13
depend:
  - BigDoors
softdepend:
  - WorldGuard
  - PlaceholderAPI
  - MythicMobs
  - NashornJs

commands:
  bigdoorsopener:
    description: open doors
    usage: "setTimed <...> | setClosed <...> | setRange <...> | invertOpen <...> | requiresPermission <...> | unregister <...> | info <...> | list | reload | about"
    aliases:
      - bdo