name: BigDoorsOpener
description: Open and close doors automatically on certain conditions
author: Hadde
version: 1.2-BETA
main: de.eldoria.bigdoorsopener.BigDoorsOpener
website: www.spigotmc.org/resources/80805/
api-version: 1.15
depend: [BigDoors]

commands:
  bigdoorsopener:
    description: open doors
    usage: "setTimed <...> | setClosed <...> | setRange <...> | invertOpen <...> | requiresPermission <...> | unregister <...> | info <...> | list | reload | about"
    aliases:
      - bdo