name: ${project.name}
description: ${project.description}
author: Hadde
version: ${project.version}
main: de.eldoria.bigdoorsopener.core.BigDoorsOpener
website: www.spigotmc.org/resources/80805/
api-version: 1.13
depend: [BigDoors]
softdepend:
  - WorldGuard
  - PlaceholderAPI
  - MythicMobs

commands:
  bigdoorsopener:
    description: open doors
    usage: "setTimed <...> | setClosed <...> | setRange <...> | invertOpen <...> | requiresPermission <...> | unregister <...> | info <...> | list | reload | about"
    aliases:
      - bdo